#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${PRATICASE_ENV_FILE:-$ROOT_DIR/.env.praticase}"
DEFINE_FILE="$ROOT_DIR/.dart_tool/praticase_env.json"
IOS_XCCONFIG="$ROOT_DIR/ios/Flutter/PratiCaseEnv.xcconfig"
MACOS_XCCONFIG="$ROOT_DIR/macos/Flutter/PratiCaseEnv.xcconfig"
WRITE_APPLE_CONFIG=true

if [[ "${1:-}" == "--dart-defines-only" ]]; then
  WRITE_APPLE_CONFIG=false
  shift
fi

if [[ "$#" -ne 0 ]]; then
  echo "Usage: scripts/sync_praticase_env.sh [--dart-defines-only]" >&2
  exit 2
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE. Create it from .env.praticase.example or sync it from Coolify." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [[ -z "${SUPABASE_URL:-${FLUTTER_SUPABASE_URL:-}}" ]]; then
  echo "SUPABASE_URL or FLUTTER_SUPABASE_URL is required." >&2
  exit 1
fi

if [[ -z "${SUPABASE_ANON_KEY:-}" ]]; then
  echo "SUPABASE_ANON_KEY is required." >&2
  exit 1
fi

if [[ -z "${AUTH_REDIRECT_URL:-}" ]]; then
  echo "AUTH_REDIRECT_URL is required." >&2
  exit 1
fi

mkdir -p "$ROOT_DIR/.dart_tool"
if [[ "$WRITE_APPLE_CONFIG" == true ]]; then
  mkdir -p "$(dirname "$IOS_XCCONFIG")" "$(dirname "$MACOS_XCCONFIG")"
fi

python3 - "$DEFINE_FILE" "$IOS_XCCONFIG" "$MACOS_XCCONFIG" "$WRITE_APPLE_CONFIG" <<'PY'
import base64
import json
import os
import pathlib
import sys

define_file = pathlib.Path(sys.argv[1])
ios_xcconfig = pathlib.Path(sys.argv[2])
macos_xcconfig = pathlib.Path(sys.argv[3])
write_apple_config = sys.argv[4] == "true"

keys = [
    "SUPABASE_URL",
    "FLUTTER_SUPABASE_URL",
    "SUPABASE_ANON_KEY",
    "AUTH_REDIRECT_URL",
]

values = {key: os.environ.get(key, "") for key in keys}
if not values["SUPABASE_URL"]:
    values["SUPABASE_URL"] = values["FLUTTER_SUPABASE_URL"]
if not values["FLUTTER_SUPABASE_URL"]:
    values["FLUTTER_SUPABASE_URL"] = values["SUPABASE_URL"]

define_file.write_text(json.dumps(values, indent=2) + "\n", encoding="utf-8")
define_file.chmod(0o600)

encoded = ",".join(
    base64.b64encode(f"{key}={value}".encode("utf-8")).decode("ascii")
    for key, value in values.items()
)

xcconfig = (
    "// Generated by scripts/sync_praticase_env.sh. Do not commit.\n"
    "PRATICASE_ENV_CONFIGURED = YES\n"
    f"PRATICASE_DART_DEFINES = {encoded}\n"
    "DART_DEFINES = $(inherited),$(PRATICASE_DART_DEFINES)\n"
)

if write_apple_config:
    for path in (ios_xcconfig, macos_xcconfig):
        path.write_text(xcconfig, encoding="utf-8")
        path.chmod(0o600)
PY

echo "PratiCase env synced:"
echo "  .dart_tool/praticase_env.json"
if [[ "$WRITE_APPLE_CONFIG" == true ]]; then
  echo "  ios/Flutter/PratiCaseEnv.xcconfig"
  echo "  macos/Flutter/PratiCaseEnv.xcconfig"
fi
